### ISSUE TITLE
sodium_add?

### ISSUE THREAD

**Issue by eviltofu** [jamesruan/sodium#4]
I'm trying to implement a client-server webSocket pair which uses Diffie-Hellman key exchange to establish a common key and sodium.SecretBox/sodium.SecretBoxOpen to encrypt the data between them. The nonce on the server always starts at 0 and increments by 2 and on the client starts at 1 and increments by 2. So on the server the nonce will be 0,2,4,6... and on the client the nonce will be 1,3,5,7...

Is it possible to include sodium_add and perhaps have Nonce implement a Add(size int) function? I am currently calling Next() twice for each nonce and that seems a bit inelegant. 

Thank you.

**Comment by jedisct1** [comment]
As an alternative, you can set the high bit to 1 for one of the sides, and just increment the nonce.
Or even better, use different keys for each direction.
