### ISSUE TITLE
Any plans for libsodium 1.0.17

### ISSUE THREAD

**Issue by udf2457** [jamesruan/sodium#8]
https://github.com/jedisct1/libsodium/releases/tag/1.0.17

Any plans ?

**Comment by jedisct1** [comment]
libsodium 1.0.17 was released 3 months ago.

**Comment by challarao** [comment]
Hello @jamesruan 

Any plans to support 1.0.14?

This adds support to secret streams API which is optimal for encrypting large files:

> The crypto_secretstream_*() API was introduced in libsodium 1.0.14.

https://libsodium.gitbook.io/doc/secret-key_cryptography/secretstream

Thanks

**Comment by jamesruan** [comment]
steam api is supported now
